-- Create maintenance settings table to control site-wide maintenance mode
CREATE TABLE IF NOT EXISTS public.maintenance_settings (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    bypass_ips TEXT[] NOT NULL DEFAULT '{}',
    bypass_cookie_secret TEXT,
    last_generated_token TEXT,
    last_generated_token_expires_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_by UUID REFERENCES auth.users(id)
);

-- Ensure there is always a single row (id = 1)
INSERT INTO public.maintenance_settings (id, is_enabled, bypass_ips)
VALUES (1, FALSE, '{}')
ON CONFLICT (id) DO NOTHING;

-- Keep updated_at in sync
CREATE OR REPLACE FUNCTION public.maintenance_settings_touch()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS maintenance_settings_set_updated_at
    ON public.maintenance_settings;

CREATE TRIGGER maintenance_settings_set_updated_at
    BEFORE UPDATE ON public.maintenance_settings
    FOR EACH ROW
    EXECUTE FUNCTION public.maintenance_settings_touch();

-- Enable RLS and lock access down to service role
ALTER TABLE public.maintenance_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role manage maintenance settings"
    ON public.maintenance_settings
    FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

COMMENT ON TABLE public.maintenance_settings IS
    'Stores global maintenance mode flag and bypass configuration. Expected single-row table (id=1).';
COMMENT ON COLUMN public.maintenance_settings.bypass_ips IS
    'Array of IP addresses that should bypass maintenance mode at the edge.';
COMMENT ON COLUMN public.maintenance_settings.bypass_cookie_secret IS
    'Optional HMAC secret used to sign maintenance bypass cookies.';
COMMENT ON COLUMN public.maintenance_settings.last_generated_token IS
    'Stores the last maintenance bypass token issued to an administrator.';
COMMENT ON COLUMN public.maintenance_settings.last_generated_token_expires_at IS
    'Timestamp for when the last bypass token expires.';
COMMENT ON COLUMN public.maintenance_settings.updated_by IS
    'References the admin user who last changed maintenance mode settings.';

ALTER TABLE public.maintenance_settings
  ADD COLUMN IF NOT EXISTS last_generated_token TEXT,
  ADD COLUMN IF NOT EXISTS last_generated_token_expires_at TIMESTAMP WITH TIME ZONE;

